### ISSUE TITLE
What is 'rigger' used for (it's a pretty big module)

### ISSUE THREAD

**Issue by torarvid** [maxogden/commonjs-html-prettyprinter#7]
Hi. After an npm install, this module takes 7424 kB on my machine. 91% of that size is the 'rigger' module, which I can't find any reference to, except in package.json.

Is there any reason why this module is needed?

If you use it in a build step or something, maybe it could be moved from "dependencies" to "devDependencies" in package.json?

**Comment by maxogden** [comment]
thanks for reporting, fixed in 0.0.10

**Comment by torarvid** [comment]
Kudos on quick reply and fix. :+1: :trophy:
